server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  h2:
    console:
      enabled: false
